---
- hosts: k8s-master-1
  tasks:
  - name: create gluster volume
    become: true
    gluster_volume:
      state: present
      force: yes
      replicas: 2
      name: kube_vol
      bricks: /glusterfs/kube_gluster
      cluster:
        - k8s-master-node-1
        - k8s-node-1
        - k8s-node-2
        - k8s-node-3

  - name: start gluster volume
    become: true
    gluster_volume:
      state: started
      name: kube_vol
  #- name: remove volume
  #  become: true
  #  gluster_volume:
  #    state: absent
  #    name: Vol1
